unique_ids:
  forms:
    Forms_Settings.Settings: H5ES3EE3HGRNCVDWW5CCAIYTETZWR4OR
    Forms_Settings.Devices: K7H5Z4W4LSMESNKSLWKAD2YG6TZWF4RY
    Form_Welcome: GELNIARZXXPQO43EYKYNHQVERZSC7I4S
    Forms_Author.Drafts: Q3GDEUKCDK4FJB25CFUF3DFH5LCNOQDX
    Forms_Editor.Genres: LLXQIM5IP6XGPVZEDQSZEDILM7AQDSY2
    Forms_Editor.Cover: OH5EFW5SZSIHKKI7VREUVFVHZ26ONKPV
    Forms_Today.Search: GCSPB5L3CE2VAEUGP5CGY5JWTEHALMAA
    Forms_Author.Published: WGKXHBU4KGFT7BD4E3HXZ66LRBBOQUZD
    Forms_Today.Bookmarks: NHWL6YIWQGSYELZBNJAIKAF7MBYEBTJG
    Forms_Today.Charts: PGEUXIW5X4F4YOKFMJY46BLO7CVSSEIN
    Forms_Editor.Publish: TXX2KSKMCGHIHXN7NEV5YVUHA44GC7TB
    Forms_Reader.Reader: OVPYDSQK2K4XVBVQFIOWCYALFCN7R3HP
    Forms_Author.Stats: AW2E7JXEYA3VPOAP6IP2KK53I3RTJMF7
    Forms_Today.Authors: SWNFH5OICIAI4L6YGWTAASFNLDVZLNWS
    Forms_Editor.Editor: X3WJFDY4LVBZT5DT2CVVBZQGMZW7QQOM
    Forms_Today.Today: AAEW5ET6AHKLA3BQP3DXMHUGWW6OG5XE
  modules:
    Forms_Author: VCIMDMYC47DHP26C7BIPUNN4FEJSCFVA
    App.Awesome: JURAY3JYFRSYT7QGJH7W7JGV26ICUEHW
    Forms_Reader: Z6LYKO4VJNJRPT2PCCWDSBCUI6KN43FH
    App.Index: VE2JKKAR7Z2TYTNDZQACOQHV6RS74DNF
    App.Works: ZMNJU5HITSUIOXJ2D7EIIGGBFNJGEA4Y
    App: SS227K7FWNDK2U3FCUVI4FRKVVBE7C2X
    Covers_Builder: FQCNQHHYWQLPIFEHJZOMA2HQQQK6CPXA
    App.User: RGEUBS7GUBIRMHTM7654F4LVFO2JVLM3
    App.Navigation: Q7A4QQE55I4DTF3MUP33TOBWFZGHKLYN
    App.Assets: SXQTJZ5JEZL7EMXG3KHLJGTVYDCJXH3E
    Forms_Editor.Cover.Contrast: GYIXTVPFO5QMHXRH3OOAZIUVARXYLOQO
    App.Editor: RCOU3FNYQW2BVWLCYXQDL7YHUOX3HJ4V
    Forms_Settings: DWFCOJXRZWVP6J4HL2PJWXVVGX3QX7XX
    Helpers: NJVKRY55LNBNWSLMMTT22LNA7I53DMQS
    App.Api: G673K3DS7UQC2TBCEDZXD4JZWFHGYFH3
    App.Settings: PPFALREHGODFTJBHPMRN5JHLHMGIRSLA
    App.Browser: VUWX3L5QBCBAWJGRYUZK7QDOQEBVWDXM
    Forms_Today: Q5EOD4S3LOC3SDVGHGHZWUTLSAEXP465
    App.Reader: UMVNMAVDPKYUKE7YVMDJODASCZXY3AHH
    Forms_Editor.Cover.ImageCover: SLSWFBO75CXMWUYGEAUGOCDXKH7V3MGQ
    Forms_Editor: J6NH76QDP6R6BYZFRT6WYDBGXLBY6KMR
  server_modules:
    CfApi: 2UO7ECGYNLIWQLBP2Y5RNJJBAVKL5PZ3
    author_publish: '1720023220512751307582866.7388'
  assets:
    html/work_cover.html: NFM35REOS5DPLOZBFWMUWKFJ326BRBWP
    md/settings.md: 7MBKYOY5NMYUAO4M66WAT2PJACGL6GM3
    html/editor/editor.html: POPQNRM4DPPJRZYXPDLDFYUNVTAVF55K
    html/form_reader_css.html: WLOWQNUQI5COOQEKXY7X2GBEBM4AQE3D
    json/genres_23.json: QGKNNHJW2BFZABVAJIH24U2ION4MUVNO
    css/forms.css: KCTY6JUDRCPJNOBTSXOLUCM4YP4B6HRW
    json/quill_publish.json: IQDVIOJZPENI22WNWWKADT66E2BTFYOK
    theme.css: J75SVNFN5B526WWL3473XJPWQMGHGNLT
    html/author/published.html: Y2ULZ7ZMF2Z2H3MDR3MSPNAJW5U7G3VA
    html/font.html: WQ77QOSK4T3NHPOJ5D45JGNAKSYM6B37
    css2/fonts.css: XSRIUWC22OGKVK57NZCMMU7TW2IIFV7K
    css2/forms.css: 3BLMKQGVE2O5LZCLGDUIKLLAJHUVT4XK
    js/viewport.js: DGQSLB7AUFRYYP655UYFNT445KCM5TWZ
    fonts/ADYS.ttf: BUYLI7FNCWKNZGRLL6B5UDGH476GW62R
    css2/settings.css: IJ5UVABEWP2TXA3FAOWU7L6ECHTCUZ6R
    .DS_Store: XTULABBSDABEHCNF6JATVNPXBE3L32NB
    navigation/reader.html: FH42DDL3TS24ZPAD2YFPZS3BSKD2ZV2Y
    navigation/today_olda.html: OXELMLECT47I75GFIU7PUOMCKBKYAJES
    html/editor/genres.html: SKMESZMOR7HUAM3TIBO3376NLBL2YPAR
    navigation/today.html: L45YS6VAIEKGPTACUBDVWRPAIFKN5JYE
    navigation/author.html: NKM4353JPJMPKSLS66LIVVC4QLCNT77T
    navigation/settings_author.html: 6WUAEIDMZ6Y6UXIMMSCXWJC5OCRBLFK7
    standard-page.html: KC6RJ3X7YOEOQ77EHCSN7ODVOCMHIGM5
    html/today/bookmarks.html: OCP6T6WEUDWAI6NRZ6OFRJUIS7NKE5YV
    json/genres_1.json: QPQHFW64S5CJPZXCMRXCCLBOR4IFEYQ2
    navigation/settings.html: IYWGTVI5ZXXCQRSYXULQ27ZYS6MYVUC4
    fonts/.DS_Store: 2MFE2SEMFBZRDTEUJT6F2ZMNNZVPJX5C
    html/today/charts.html: 5NCYFHZ4MVKM7AOFB27H5PTKJUT2IGTW
    html/today/search.html: QQBLMT6X5FLPAXIGLT7GZXVNYBOJF4TZ
    md/welcome.md: J4IIA3J6ZGIK44E6UBJE2O37VV2Y7DUG
    html/author/stats.html: Q6I4EP77UWXS7RA7L566WQCRTHEMATXN
    html/test.html: OSGLI4HAF2BVZPENYOHJDVXWB3P7BKO7
    html/author/drafts.html: BVIH32IATE7QB3O4LV5WJ5LRKJOI7V5A
    md/settings_author.md: E5LG5RLGIBAECLY5HJP5ZZMIDEOLSGEE
    json/quill_options.json: VVDZBPXKVUQANVA2TMG2P6GWP3Y3TXZS
    json/work_data_example.json: 5HHI4K7EK4GP5Y2ACTIWGXN6RN7N5YCI
    css2/root.css: 3IYB522F4XZKXMKSI2IYFQM634P2X4HO
    html/today/authors.html: KMQ4U5XACG2TCWTODZSBO2K4QJHK7TXE
    navigation/editor.html: JKTYSR2YYHJS5M2GNG5V6UMW56E5QHIL
    css/elements.css: 7ZUGAWRDW2UOTTGGDQNDVIQ36ARYYIYV
    html/reader/reader.html: 7HIEKT4ADCBSG25MGM3WR3HGQSGMYSMZ
    css/fonts.css: 2H4XT7IFUE3MV3PGSXZAQN5ICWGNFRL7
    css2/work_card.css: YXFEV7BY7N25YBUK6K3644D7FLRTOYJT
    chetemecover.webp: '1719567099895331483774009.2652'
    html/settings/visuals.html: QPO7EAWKDPGWF6OE6WJTK7SA4YMMOKRZ
    css/work_card.css: '1719581290993392831111930.88116'
    json/genres.json: ZN6LHW5KXOLPYUMWOALEB7VJTRVYJULZ
    html/today/today.html: JVRRNOSQYYGEXC3US4UCPSMER56T4STW
    theme copy.css: FZH3WVLDLXBVX6JIC3VULCSCLCI62ZVH
    html/welcome.html: 2KGJ6TWDL4STK6E3JBE55NSGCDSRTXBS
    json/fonts.json: CVUVN5763KYKJBPM3MSWQ4EJWSID3M6G
    html/keyword.html: CWU5DFJIJBMC7K57TTEIWZZDSIN4FEFW
    html/form.html: I4T3IAFE6N3YYL5WXG57IUWRMO5CXSJB
    html/editor/cover.html: ZBKIU4TRUFGLUGT4J4PFCUBMKKI3EUMD
    navigation/nav_forms.json: IBBOTSNEV27BRMIDQUFULSNYDXWQPS74
    md/settings_devices.md: VSATR4HTTDMOPJVPO3KX2CX5FGKC7JS3
    original_theme.css: JOO4UVTDVTKOPGK75I5IDE2S5L6D3GSI
    json/awesome.json: WBLZWF3DDXKCCJGLAXPYY35QKIN7ZML5
    css/navigation.css: '1719581267989773394371737.5164'
    html/editor/publish.html: NKEX3TICLMMYHFVFAJGUZETLWXZ6Z4VA
    navigation/nav_bars.json: 4C7V4X4BPNQDHOHHZWH3VSC3PDOVFKXU
    html/settings/devices.html: VAEHYRWN7O2Q2T57A6BEDYVVMJNY456T
    json/genres_01.json: LMFUVWBLEWIPHRWHCEDAJ3JZNQ33VK4T
    json/work_data.json: IQ3JY3MCGJHKIES6P55UC3YMFQVYKOEX
    html/icon.html: YN4TEOZ5IZJA4OSDJ2AIOMZW2NOP57FK
    css/text.css: 7OFAKV7I2CO2WSRU2JBIWTVF7ANI5OWS
  scripts: {}
