unique_ids:
  forms:
    Form_Welcome: GELNIARZXXPQO43EYKYNHQVERZSC7I4S
    Forms_Settings.Author: POE7XRMCKTME5IDON5GXLGHY4N5UAFTP
    Forms_Settings.Devices: K7H5Z4W4LSMESNKSLWKAD2YG6TZWF4RY
    Forms_Settings.Settings: H5ES3EE3HGRNCVDWW5CCAIYTETZWR4OR
    Forms_Today.Today: AAEW5ET6AHKLA3BQP3DXMHUGWW6OG5XE
    _ExampleForms._BlankPanel: '1719567338446752150169180.0055'
    _ExampleForms._CustomHtml: '1719567350360418900194031.20526'
    _ExampleForms._Form1: EMWKW5UMAJCZTSVLWP2OC3AQOMEVIJ5E
  modules:
    App.Index: VE2JKKAR7Z2TYTNDZQACOQHV6RS74DNF
    App: SS227K7FWNDK2U3FCUVI4FRKVVBE7C2X
    App.User: RGEUBS7GUBIRMHTM7654F4LVFO2JVLM3
    App.Navigation: Q7A4QQE55I4DTF3MUP33TOBWFZGHKLYN
    App.Assets: SXQTJZ5JEZL7EMXG3KHLJGTVYDCJXH3E
    Forms_Settings: DWFCOJXRZWVP6J4HL2PJWXVVGX3QX7XX
    App.Api: G673K3DS7UQC2TBCEDZXD4JZWFHGYFH3
    App.Settings: PPFALREHGODFTJBHPMRN5JHLHMGIRSLA
    App.Browser: VUWX3L5QBCBAWJGRYUZK7QDOQEBVWDXM
    Forms_Today: Q5EOD4S3LOC3SDVGHGHZWUTLSAEXP465
    _ExampleForms: '1719573334345578319361221.5146'
  server_modules: {}
  assets:
    md/settings.md: 7MBKYOY5NMYUAO4M66WAT2PJACGL6GM3
    css/settings.css: HEDZ42LDMQANMZHJSZQMQJ32FBUBSLL2
    theme.css: J75SVNFN5B526WWL3473XJPWQMGHGNLT
    js/viewport.js: DGQSLB7AUFRYYP655UYFNT445KCM5TWZ
    fonts/ADYS.ttf: BUYLI7FNCWKNZGRLL6B5UDGH476GW62R
    html/today.html: SFW3ECOZ6MQ7VM47PO4FAY5XB4AWX5L7
    navigation/today.html: L45YS6VAIEKGPTACUBDVWRPAIFKN5JYE
    standard-page.html: KC6RJ3X7YOEOQ77EHCSN7ODVOCMHIGM5
    navigation/settings.html: IYWGTVI5ZXXCQRSYXULQ27ZYS6MYVUC4
    html/settings.html: RM6MD37HQZB2POE6RRVK775X2SR6I365
    md/welcome.md: J4IIA3J6ZGIK44E6UBJE2O37VV2Y7DUG
    html/test.html: OSGLI4HAF2BVZPENYOHJDVXWB3P7BKO7
    md/settings_author.md: E5LG5RLGIBAECLY5HJP5ZZMIDEOLSGEE
    md/settings_user.md: QMP7NIDOKIUKZGFM3P5V2H4B5CFCDNLS
    chetemecover.webp: '1719567099895331483774009.2652'
    css/work_card.css: '1719581290993392831111930.88116'
    html/welcome.html: 2KGJ6TWDL4STK6E3JBE55NSGCDSRTXBS
    css/root.css: RU3CVTVNUAUHAFGMSOPL2MZAOJHRD3CF
    navigation/nav_forms.json: IBBOTSNEV27BRMIDQUFULSNYDXWQPS74
    css/navigation.css: '1719581267989773394371737.5164'
    navigation/nav_bars.json: 4C7V4X4BPNQDHOHHZWH3VSC3PDOVFKXU
    html/anvil.html: UUO7TUUWJYFDWPOUHB626L745BY7PBPP
    css/text.css: 7OFAKV7I2CO2WSRU2JBIWTVF7ANI5OWS
  scripts: {}
